---
- name: "Verify"
  hosts: "all"
  gather_facts: false
  become: true

  vars:
    resilio_docker_name: "resilio-test-container"
    resilio_docker_network: "resilio-docker-test-network"
    resilio_docker_volume_name: "resilio-test-volume"

  tasks:
    - name: "Get info on data volume"
      community.docker.docker_volume_info:
        name: "{{ resilio_docker_volume_name }}"
      register: "_volume_info_data"

    - name: "Verify data volume"
      ansible.builtin.assert:
        that:
          - "_volume_info_data.exists"

    - name: "Get info on default network"
      community.docker.docker_network_info:
        name: "{{ resilio_docker_network }}"
      register: "_network_info"

    - name: "Verify default network"
      ansible.builtin.assert:
        that:
          - "_network_info.exists"

    - name: "Get info on container: {{ resilio_docker_name }}"
      community.docker.docker_container_info:
        name: "{{ resilio_docker_name }}"
      register: "container_info"

    - name: "Verify container exists and is running: {{ resilio_docker_name }}"
      ansible.builtin.assert:
        that:
          - "container_info.exists"
          - "container_info.container['State']['Running']"

    - name: "Extract HostConfig"
      ansible.builtin.set_fact:
        _resilio_host_config: "{{ container_info.container['HostConfig'] }}"

    - name: "Verify container is configured correctly"
      ansible.builtin.assert:
        that:
          - "_resilio_host_config['Mounts'][0]['Type'] == 'volume'"
          - "_resilio_host_config['Mounts'][0]['Source'] == '{{ resilio_docker_volume_name }}'"
          - "_resilio_host_config['Mounts'][0]['Target'] == '/mnt/sync'"
          - "_resilio_host_config['Mounts'][1]['Type'] == 'bind'"
          - "_resilio_host_config['Mounts'][1]['Source'] == '/var/log'"
          - "_resilio_host_config['Mounts'][1]['Target'] == '/mnt/mounted_folders/logs'"
          - "_resilio_host_config['Mounts'][2]['Type'] == 'bind'"
          - "_resilio_host_config['Mounts'][2]['Source'] == '/etc'"
          - "_resilio_host_config['Mounts'][2]['Target'] == '/mnt/mounted_folders/etc2'"
